# Dependabot configuration for automated dependency updates
# This helps keep dependencies secure and up-to-date

version: 2
updates:
  # Enable version updates for npm dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    # Group minor and patch updates together to reduce PR noise
    groups:
      development-dependencies:
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"
      production-dependencies:
        dependency-type: "production"
        update-types:
          - "minor"
          - "patch"
    # Security updates are always separate and immediate
    labels:
      - "dependencies"
      - "automated"
    commit-message:
      prefix: "chore"
      include: "scope"
    # Review for major version updates
    reviewers:
      - "Krosebrook"
    # Auto-approve minor and patch updates for faster turnaround
    target-branch: "main"

  # Monitor GitHub Actions for updates
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "ci"
