  name: CI

  on:
    push:
      branches: [main, develop, Update2.0]
    pull_request:
      branches: [main, Update2.0]

  jobs:
    validate:
      name: Comprehensive Validation
      runs-on: ubuntu-latest

      steps:
        - name: Checkout code
          uses: actions/checkout@v5

        - name: Setup Node.js
          uses: actions/setup-node@v6
          with:
            node-version: '20'
            cache: 'npm'

        - name: Run comprehensive validation
          run: npm run validate:imports

    test:
      name: Test and Lint
      runs-on: ubuntu-latest
      strategy:
        matrix:
          node-version: [20, 22]

      steps:
        - name: Checkout code
          uses: actions/checkout@v5

        - name: Setup Node.js
          uses: actions/setup-node@v6
          with:
            node-version: ${{ matrix.node-version }}
            cache: 'npm'

        - name: Install dependencies
          run: npm ci

        - name: Check code formatting
          run: npm run format:check

        - name: Run linter
          run: npm run lint

        - name: Run tests
          run: npm test

        - name: Build project
          run: npm run build

    security:
      name: Security Check
      runs-on: ubuntu-latest

      steps:
        - name: Checkout code
          uses: actions/checkout@v5

        - name: Setup Node.js
          uses: actions/setup-node@v6
          with:
            node-version: '20'

        - name: Run security audit
          run: npm audit --audit-level=moderate
          continue-on-error: true

        - name: Check for vulnerabilities
          run: npm audit --audit-level=high
